# Config relating to the Lazygit UI
gui:
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-author-color
  authorColors:
    "egoreast": "blue"

  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-branch-color
  branchColorPatterns:
    "main": "red"
    "dev": "green"
    "test": "yellow"

  # Custom icons for filenames and file extensions
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-files-icon--color
  # customIcons:
  #   # Map of filenames to icon properties (icon and color)
  #   # filenames: {}
  #
  #   # Map of file extensions (including the dot) to icon properties (icon and color)
  #   extensions:
  #     ".md":
  #       "icon": ""
  #       "color": "blue"
  #     ".css":
  #       "icon": "\ue6b8"
  #       "color": "red"

  # If true, capture mouse events.
  # When mouse events are captured, it's a little harder to select text: e.g. requiring you to hold the option key when on macOS.
  mouseEvents: false

  # Config relating to colors and styles.
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#color-attributes
  theme:
    # Border color of focused window
    activeBorderColor:
      - magenta
      - bold

    # Color of keybindings help text in the bottom line
    optionsTextColor:
      - magenta

    # Background color of selected line.
    # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#highlighting-the-selected-line
    selectedLineBgColor:
      - magenta

  # If true, show the number of lines changed per file in the Files view
  showNumstatInFilesView: true

  # Whether to show the divergence from the base branch in the branches view.
  # One of: 'none' | 'onlyArrow'  | 'arrowAndNumber'
  showDivergenceFromBaseBranch: none

  # Config relating to the spinner.
  spinner:
    # The frames of the spinner animation.
    frames:
      - 
      - 
      - 
      - 
      - 
      - 

    # The "speed" of the spinner in milliseconds.
    rate: 70

# Config relating to git
git:
  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md
  paging:
    # Value of the --color arg in the git diff command. Some pagers want this to be set to 'always' and some want it set to 'never'
    colorArg: always

    # e.g.
    # diff-so-fancy
    # delta --dark --paging=never
    # ydiff -p cat -s --wrap --width={{columnWidth}}
    # pager: diff-so-fancy
    pager: delta --paging=never --line-numbers --features=collared-trogon-egoreast --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

    # If true, Lazygit will use whatever pager is specified in `$GIT_PAGER`, `$PAGER`, or your *git config*. If the pager ends with something like ` | less` we will strip that part out, because less doesn't play nice with our rendering approach. If the custom pager uses less under the hood, that will also break rendering (hence the `--paging=never` flag for the `delta` pager).
    useConfig: false

    # e.g. 'difft --color=always'
    externalDiffCommand: ""

  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#predefined-commit-message-prefix
  commitPrefix: []

  # See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#predefined-commit-message-prefix
  commitPrefixes:
    exarh-web: # This is repository folder name
      - pattern: "^(\\w+\\-\\w+#).*"
        replace: "$1 "

# See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md#custom-pull-request-urls
services: {}
