# default -- https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml
[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_translit = false
show_hidden = true
linemode = "size"

[preview]
wrap = "yes"
max_width = 600
max_height = 900

[plugin]
prepend_previewers = [
  { name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { name = "*.csv", run = 'piper -- bat -p --color=always "$1"' },
  # Archive previewer
  { name = "*.tar*", run = 'piper --format=url -- tar -t -f "$1"' },
  # { mime = "application/*zip", run = 'piper --format=url -- unzip -l "$1"' },
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-bzip2", run = "ouch" },
  { mime = "application/x-7z-compressed", run = "ouch" },
  { mime = "application/x-rar", run = "ouch" },
  { mime = "application/x-xz", run = "ouch" },
  { mime = "application/xz", run = "ouch" },
  # { mime = "application/x-bzip2", run = 'piper --format=url -- tar -t -f "$1"' },
  # { mime = "application/x-7z-compressed", run = 'piper --format=url -- 7z l "$1"' },
  # { mime = "application/x-xz", run = 'piper --format=url -- tar -t -f "$1"' },
  # { mime = "application/xz", run = 'piper --format=url -- tar -t -f "$1"' },
]

[opener]
extract = [
  { run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
