#!/usr/bin/env bash
#
# power-profiles-daemon implementation:
# needs package power-profiles-daemon installed and the service running see here:
# https://wiki.archlinux.org/title/CPU_frequency_scaling#power-profiles-daemon
# used in i3-blocks: ~/.config/i3/i3blocks.conf together with: ~/.config/i3/scripts/power-profiles

# script to show current power profile

# assign tags or translations to each profile
declare -A tags
declare -A colors

tags=(
  [performance]="Performance"
  [balanced]="Balanced"
  ['power-saver']="Power saver"
)
colors=(
  [performance]="#a8b5e0"   # Мягкий лавандовый (агрессивный режим)
  [balanced]="#b5e0a8"      # Нежно-мятный (баланс)
  ['power-saver']="#e0a8b5" # Тёплый розовый (энергосбережение)
)

# Get current profile
current_profile=$(powerprofilesctl get)

# Get tag from the array
profile_tag=${tags[$current_profile]}
profile_color=${colors[$current_profile]}

# Show tag on i3block
echo "<span color='${profile_color}'>${profile_tag:-$current_profile}</span>"
