password = []
size = [
    9,
    503,
    1900,
    1016,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'shrink'
image_quality = ''
custom_image_quality = []
show_remote_cursor = false
disable_wallpaper_and_aero = false
lock_after_session_end = false
privacy_mode = false
port_forwards = []
direct_failures = 0
disable_audio = false
disable_clipboard = false
enable_file_transfer = false
note = ''
show_quality_monitor = false
view_mode = false

[options]
alias = 'Алеся'

[info]
username = 'валя'
hostname = 'laptop-pj96afq7'
platform = 'Windows'

[transfer]
write_jobs = []
read_jobs = []

[chat_storage]
messages = []
